// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfwqdqtfxzxezrxahakb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmd3FkcXRmeHp4ZXpyeGFoYWtiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI0MTg0NjgsImV4cCI6MjA3Nzk5NDQ2OH0.HP68wMTYiAffJYF8jFgeMc9UCskM80ThbSynw3YlK2c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});